# Generated by Django 2.2.5 on 2021-04-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210420_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_book_genre',
            field=models.CharField(blank=True, choices=[('소설', '소설'), ('수필(에세이)', '수필(에세이)'), ('시', '시'), ('그림책', '그림책'), ('만화책', '만화책')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_movie_genre',
            field=models.CharField(blank=True, choices=[('액션', '액션'), ('SF(공상과학)', 'SF(공상과학)'), ('코미디', '코미디'), ('스릴러', '스릴러'), ('전쟁', '전쟁'), ('운동', '운동'), ('판타지', '판타지'), ('음악', '음악'), ('멜로', '멜로')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('kr', 'Korean')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=4, null=True),
        ),
    ]
