# Generated by Django 2.2.5 on 2021-05-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Book Genre',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('favorite_book_genre', models.CharField(blank=True, choices=[('소설', '소설'), ('수필(에세이)', '수필(에세이)'), ('시', '시'), ('그림책', '그림책'), ('만화책', '만화책')], max_length=20)),
                ('favorite_movie_genre', models.CharField(blank=True, choices=[('액션', '액션'), ('SF(공상과학)', 'SF(공상과학)'), ('코미디', '코미디'), ('스릴러', '스릴러'), ('전쟁', '전쟁'), ('운동', '운동'), ('판타지', '판타지'), ('음악', '음악'), ('멜로', '멜로')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie_Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Movie Genre',
            },
        ),
    ]
